DROP TABLE IF EXISTS url_checks;
DROP TABLE IF EXISTS urls;

CREATE TABLE urls (
  id                            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  name                          VARCHAR(255),
  created_at                    TIMESTAMP NOT NULL,
  CONSTRAINT pk_url_id PRIMARY KEY (id)
);

create table url_checks (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    url_id      BIGINT  REFERENCES urls (id)            NOT NULL,
    status_code integer                                 NOT NULL,
    title       varchar(255),
    h1          varchar(255),
    description text,
    created_at  timestamp                               NOT NULL,
    CONSTRAINT pk_url_checks PRIMARY KEY (id)
);
